# Generated by Django 3.1.2 on 2020-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201012_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='processado',
            field=models.BooleanField(default=True, verbose_name='Processado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
