# Generated by Django 3.1.2 on 2020-10-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelOptions(
            name='regra',
            options={'verbose_name': 'Regra', 'verbose_name_plural': 'Regras'},
        ),
    ]
